OCRapp/urls.py
from django.urls import path
from . import views

app_name = 'OCRapp'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('upload/', views.upload_image, name='upload_image'),
    path('view/<int:pk>/', views.view_image, name='view_image'),
    path('view_clean_data/<int:pk>/', views.view_clean_data, name='view_clean_data'),
    path('export_json/<int:pk>/', views.export_to_JSON, name='export_to_JSON'),
]

OCRproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('OCRapp.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'base_style.css' %}">
    <title>Passport OCR</title>
</head>
<body>
    <nav class="navbar">
        <a href="{% url 'OCRapp:home' %}">PyCORJT</a>
        <a href="https://github.com/PremR22">Link to Code</a>
    </nav>
    <div id="spacer"></div>
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/homepage.html
{% extends "base.html" %}
   
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'homepage_style.css' %}">

<div class="heading">
    <h1>Welcome to PyCORJT</h1>
    <h3>Extract and View Passport Details</h3>
    <p>Welcome to my Passport Data extractor. I made this project to learn more about Django and it's working.</p>
    <hr>
    <h3>How this works</h3>
    <p>Upload Images -> Extract Data -> Export JSON</p>
<div class="button">
    <a href="{% url 'OCRapp:upload_image' %}">Get Started!</a>
</div>
{% endblock content %}